name: low_age_app_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_naver_map: ^1.4.1+1
  location: ^8.0.1
  http: ^1.2.0
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.0
  # [삭제] lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
